### ISSUE TITLE
有考虑合并HITsz-Automation-Opensource吗？

### ISSUE THREAD

**Issue by TangLongbin** [HITSZ-Auto/HITSZ-OpenAuto#13]
我目前了解到的咱学校自动化的开源库除了这这个仓库外还有一个Automation-Opensource的仓库，不过那个仓库已经8个月没人维护了，里面有不少资料是这个仓库没有的，能合并在一起维护我觉得挺好的。我不是仓库owner，目前是自动化大三在读，同时也很想参与这个仓库的维护，自救群还是太有限了。

**Comment by TangLongbin** [comment]
另外想问一下这个仓库目前主要是RM的队员在维护吗？

**Comment by lmh12138** [comment]
第一个问题
那个仓库是17级一个学长创立的仓库，我并未取得将学长的资料合并到我的仓库的权限，之后我会尝试联系一下学长，看看能否取得权限。
第二个问题
想参与仓库维护的话，非常欢迎，但目前考虑到自动化大三比较忙，我的建议是等大四再把精力放在维护仓库上，毕竟你们现在还是要以保研考研就业为主
第三个问题
不是，仓库维护只有我一个人来做，有RM的东西是因为我之前是RM的队员

**Comment by TangLongbin** [comment]
了解，以后我有资料将会以pull request的形式申请合并到仓库
