### ISSUE TITLE
21级马原串级整理

### ISSUE THREAD

**Issue by kowyo** [HITSZ-Auto/HITSZ-OpenAuto#14]
#  马克思主义基本原理串讲课整理

2022.12.9 - 第一版发布

2022.12.10 - 修改了错别字，根据21年考试题进行了内容的补充

[TOC]

# 导论

## **一、什么是马克思主义**

1. **马克思主义的三大组成部分** ：马克思主义哲学，马克思主义政治经济学，科学社会主义。

2. **马克思主义基本原理：** 对马克思主义立场、观点、方法的集中概括。

3. **基本立场：**马克思主义观察、分析、解决问题的立足点和出发点。以无产阶级的解放和全人类的解放为己任，以人的自由全面发展为目标。

   **基本观点：** 关于自然、社会和人类思维发展一般规律的科学认识，是对人类思想成果和社会实践经验的科学总结。

   **基本方法：** 建立在辩证唯物主义和历史唯物主义世界观和方法论基础上，指导我们正确认识世界和改造世界的思想方法和工作方法。（实事求是、辨证分析、社会基本矛盾和主要矛盾分析法、历史分析法、阶级分析法......

## **二、马克思主义的创立与发展**

有深刻的社会、阶级基础、思想渊源。

**理论来源：**德国古典哲学（辩证法思想）、英国古典政治经济学（劳动创造价值的思想）、英法两国的空想社会主义（对资本主义社会的批判和对未来社会的展望）。

马克思的两个“伟大发现”是：剩余价值理论和唯物主义的历史观。

# 第一章 世界的物质性及发展规律

### **一、物质及其存在方式**

1. 哲学基本问题

$$
哲学基本问题
\left\{ 
\begin{matrix}
存在和思维、物质和意识谁为本原（何者为第一性） \\
存在和思维、意识是否具有同一性的问题 \\
\end{matrix}
\right.
$$

2. 马克思批判了旧唯物主义对物质世界的直观、消极的理解，强调要从能动的实践出发去把握现实世界。

3. 列宁对物质作了全面的科学的规定（**物质的定义**）：物质就是不依赖于人类的意识而存在，并能为人类的意识所反映的客观实在。

### **二、物质与意识的辩证关系**

1. 物质与意识的辩证关系

   1. 物质决定意识，意识是物质的产物
   2. 意识的能动作用
      1. 意识具有目的性和计划性
      2. 意识具有创造性
      3. 意识具有指导实践改造客观世界的作用
      4. 意识具有调控人的行为和生理活动的作用

2. 世界的物质统一性（世界统一于物质）

   世界的物质统一性告诉我们，在认识世界和改造世界的过程中，摒弃一切无视客观世界及其规律性的思想观念，遵循**一切从实际出发、实事求是**的原则 。

   我们要从我国社会主义初级阶段的最大国情出发，既要看到**我国仍处于并将长期处于社会主义初级阶段的基本国情没有改变**，也要看到**我国的社会主要矛盾发生了变化，已经转化为人民日益增长的美好生活需要和不平衡不充分发展之间的矛盾**。

   

### **一、对立统一规律是事物发展的根本规律**

1. 矛盾的同一性和斗争性

2. 矛盾的普遍性和特殊性

   1. 普遍性：矛盾无时不在，无处不有

   2. 特殊性：各个具体事物的矛盾、每一个矛盾的各个方面在发展的不同阶段上各有其特点。

   3. 普遍性和特殊性的辩证关系：矛盾的普遍性即矛盾的共性，矛盾的特殊性即矛盾的个性。任何现实存在事物的矛盾都是共性和个性的有机统一，共性寓于个性之中，没有离开个性的共性，也没有离开共性的个性。

3. 坚持两点论和重点论的统一

   “两点论”和“重点论”的统一要求我们，看问题既要全面地看，又要看主流、大势、发展趋势

### 二、**量变质变规律**

**辩证关系：** 量变是质变的必要准备；质变是量变的必然结果；量变和质变相互渗透。

**方法论意义：** 在认识和处理问题时，要掌握适度原则

### **三、 否定之否定规律**

1. 辩证否定观的基本内容：

​				第一，否定是事物的自我否定，是事物内部矛盾运动的结果

​				第二，否定是事物发展的环节

​				第三，否定是新旧事物联系的环节

​				第四，辩证否定的实质是“扬弃”，是新事物对旧事物既批判又继承，既克服其消极因素又保留其积极因素

### **四、联系和发展的基本环节**

（一）内容与形式

（二）本质与现象

（三）原因与结果

（四）必然与偶然

（五）现实与可能 

## **第三节 唯物辩证法是认识世界和改造世界的根本方法**

P43 - P44

# **第二章 实践与认识及其发展规律**

实践性是马克思理论区别于其他理论的根本特征。

### 一、实践的本质和基本结构

**实践的基本特征：**客观实在性，自觉能动性和社会历史性

**实践的基本结构：**

1. 实践主体：具有一定的主体能力、从事现实社会实践活动的人
2. 实践客体：实践活动所指向的对象
3. 实践中介：各种形式的工具、手段以及程序和方法

**实践形式的多样性：**

1. 物质生产实践（最基本的实践活动）

2. 社会政治实践（人们之间的社会交往和政治活动）

3. 科学文化实践(创造精神文化产品)

4. 虚拟实践（通过数字中介系统在虚拟空间进行）

### **二、认识的本质和过程**

$$
辩证唯物主义认识论两大特点
\left\{ 
\begin{matrix}
把实践的观点引入认识论 \\
把辩证法应用于反映论考察认知的发展过程 \\
\end{matrix}
\right.
$$

**（一）从实践到认识（第一次飞跃）**

**感性认识：**人们在实践基础上，由感觉器官直接感受到的关于事物的现象、事物的外部联系、事物的各个方面的认知

**理性认识：**人们借助抽象思维，在概括整理大量感性材料的基础上达到的关于事物本质、全体、内部联系和事物自身规律性的认识

**感性认识与理性认识的辩证统一：** 

1. 感性认识有待于发展和深化为理性认知
2. 理性认识依赖于感性认识
3. 感性认识和理性认识相互渗透，相互包含

**（二）从认识到实践（第二次飞跃）**

**必要性和重要性：**

1. 认识世界是为了改造世界
2. 认识的真理只有在实践当中才能得到检验和发展

#### **（一）真理的客观性**

真理的内容是对客观事物及其规律的正确反映，真理中包含着不依赖于人和人的意识的客观内容。

真理的客观性决定了真理的一元性。真理的一元性是指在同一条件下对于特定的认识客体的真理性认识只有一个。只针对真理的客观内容而言。

#### **（二）真理的绝对性与相对性**

真理的绝对性：是指真理主客观统一的确定性和发展的无限性。

真理的相对性：是指人们在一定条件下对客观事物及其本质和发展规律的正确认识总是有限度的、不完善的。

真理的绝对性和相对性的辩证统一：二者既相互依存，也相互包含。

#### **（三）真理与谬误**

谬误含义：所谓谬误，是同客观事物及其发展规律相违背的认识，是对客观事物及其发展规律的歪曲反映。

真理和谬误的对立统一关系：

第一，真理与谬误相互对立

第二，真理与谬误又是相对的，它们在一定条件下能够相互转化。

真理和谬误的对立统一关系表明，真理总是同谬误相比较而存在、相斗争而发展的。

### **二、真理的检验标准**

实践是检验真理的唯一标准，是由**真理的本性**和**实践的特点**所决定的：

**真理的本性**在于主观和客观相符合

从**实践的特点**来看，实践具有直接现实性，而实践的直接现实性是它的客观实在性的具体表现。

### **三、真理与价值的辩证统一**

**价值的含义：** 价值是指在实践基础上形成的主体和客体之间的意义关系。

**价值的基本特性：** 

1. 主体性：价值直接同主体相联系，始终以主体为中心
2. 客观性：客体对于主体的意义不依赖于主体的主观意识而存在
3. 多维性：每个主体的价值关系具有多样性
4. 社会历史性：主体和客体的不断变化决定了价值的社会历史性特点

**真理与价值的辩证统一关系：**

1. 一方面，价值尺度必须以真理为前提。脱离了真理尺度，价值尺度就偏离合理的、正确的轨道。
2. 另一方面，人类自身需要的内在尺度，推动着人们不断发现新的真理。脱离了价值尺度，真理就缺失了主体意义。

# **第三章 人类社会及其发展规律**

## **前言**

马克思和恩格斯创立的历史唯物主义实现了社会历史观的伟大变革，为我们正确认识人类社会历史及其发展趋势，准确把握社会发展的动力因素，准确把握人民群众和杰出人物在历史中的作用提供了科学的理论指导。

#### **（一）两种根本对立的历史观**

社会存在与社会意识的关系问题 ，是社会历史观的基本问题：

- 唯物史观：社会存在决定社会意识。

- 唯心史观：社会意识决定社会存在。

#### **（二）社会存在**与社会意识

**社会存在：** 是指社会物质生活条件，是社会生活的物质方面，主要包括自然地理环境、人口因素和物质生产方式。

**社会意识：** 是社会存在的反映，是社会生活的精神方面。

**辩证关系：**

1. 社会存在决定社会意识。

2. 社会意识是社会存在的反映，并反作用于社会存在。

#### **（一）生产力与生产关系**

1. **生产力**是人类在生产实践中形成的改造和影响自然以使其适合社会需要的物质力量。

   科学技术是生产力中的重要因素，是先进生产力的集中体现和主要标志，是第一生产力。

2. **生产关系**是人们在物质生产过程当中形成的不以人的意志为转移的经济关系

3. 辩证关系：

   第一，生产力决定生产关系

   第二，生产关系反作用于生产力，当生产关系适合生产力发展的客观要求时，对生产力的发展起推动作用；当生产关系不适合生产力发展的客观要求时，就会阻碍生产力的发展。

   第三，生产力与生产关系的相互作用是一个过程，表现为二者的矛盾运动，这种矛盾运动中内在的、本质的、必然的联系，就是**生产关系一定要适合生产力状况的规律**。

#### **（二）经济基础与上层建筑**

1. 经济基础：是指由社会一定发展阶段的生产力所决定的生产关系的总和。

2. 上层建筑：是建立在一定经济基础之上的意识形态以及与之相适应的制度、组织和设施。

   （在整个上层建筑中，政治上层建筑居主导地位，国家政权是核心）

3. 辩证关系：经济基础和上层建筑是辩证统一的。

   首先，经济基础决定上层建筑。

   其次，上层建筑对经济基础具有反作用。上层建筑为自己的经济基础的形成和巩固服务，确立或维护其在社会中的统治地位。

   再次，经济基础与上层建筑的相互作用构成二者的矛盾运动。

   最后，经济基础和上层建筑之间的内在联系构成了上层建筑一定要适应经济基础状况的规律。

### **（一）交往及其作用**

交往的作用：

1. 促进生产力的发展
2. 促进社会关系的进步
3. 促进文化的传播和发展
4. 促进人的全面发展

### **（二）世界历史的形成和发展**

**生产方式的发展变革**是世界历史形成和发展的基础。

## **第二节 社会历史发展的动力**

**社会历史发展的根本动力：**社会基本矛盾。直接动力：阶级斗争。

改革在社会历史是发展中的重要作用集中体现在：它是在一定程度上解决社会基本矛盾、促进生产力发展、推动社会进步的有效途径和手段。

### **科学技术在社会发展中的作用**

首先，对生产方式产生了深刻影响。其一，改变了社会生产力的构成要素。其二，改变了人类的劳作形式。其三，改变了社会经济结构，特别是导致产业结构发生变革。

其次，对生活方式产生了巨大影响。现代科技革命把人们带入了信息时代，要求人们不断更新和充实知识，以适应时代发展的需要。现代信息技术为人民提供了处理、存储、传递信息的手段，给人们的学习、工作、生活带来了极大便利。现代化的交通、通信等手段，为人们的交往提供了方便。劳动生产率的提高，是人们支配的闲暇时间增多，为人的自由而全面的发展创造了更多条件。

最后，促进了思维方式的变革。现代科技革命对人的思维方式产生了重要影响，主要表现为新的科学理论和技术手段通过影响思维主体、思维客体和思维工具，引起了思维方式的变革。

### **正确把握科学技术的社会作用**

首要的就是要有合理的社会制度保障科学技术的正确运用，始终坚持使科学技术为人类社会的健康发展服务，让科学技术为人类造福。

### **一、人民群众是历史的创造者**

人民群众是社会历史的主体，是历史的创造者。

决定作用体现在：

1. 人民群众是**社会物质财富**的创造者
2. 人民群众是**社会精神财富**的创造者
3. 人民群众是**社会变革**的决定力量

但要注意，人民群众创造历史的活动受到一定社会历史条件的制约。（经济条件、政治条件，精神文化条件）

唯物史观关于人民群众是历史的创造者的原理，要求我们坚持马克思主义群众观点，贯彻党的群众路线。

无产阶级政党的群众路线：

**群众观点：**坚信人民群众自己解放自己，全心全意为人民服务，一切向人民群众负责，虚心向群众学习。

**路线：**一切为了群众，一切依靠群众，从群众中来，到群众中去。

### **二、个人在社会历史中的作用**

**杰出人物**是历史人物中对推动历史发展作出重要贡献或起重要作用的人。

评价历史人物时应该坚持**历史分析法**和**阶级分析方法**。

### **三、群众、阶级、政党、领袖的关系**

群众划分阶级，阶级由政党领导，政党由领袖主持。群众、阶级、政党、领袖环环相扣、相互依存，构成一个有机整体。为此，要始终坚持党的群众观点和群众路线，不断巩固党的阶级基础和群众基础，确保党的坚强领导核心地位，更好地发挥人民领袖的领导作用，不断把中国特色社会主义伟大事业推进。

# **第四章 资本主义的本质及规律**

#### **（一） 商品经济产生的历史条件**

**自然经济：**自给自足经济，指生产是为了直接满足生产者个人或经济单位的需要，而不是为了交换的经济形式

**商品经济：**是以交换为目的而进行生产的经济形式，是一定社会历史条件的产物。

##### 商品二因素

商品二因素：使用价值、价值。使用价值是指满足人的某种需求的有用性。价值是凝结在商品中的无差别的一般人类劳动。

使用价值和价值是对立统一的关系。

其对立性表现在：商品的使用价值二号价值是相互排斥的，二者不可兼得。要获得商品的价值，就必须要放弃商品的使用价值；要得到商品的使用价值，就不能得到商品的价值。

其统一性表现在：作为商品，必须同时具有使用价值和价值两个因素。使用价值是价值的物质承担者，价值寓于使用价值之中。

##### 劳动的二重性

劳动分为具体劳动和抽象劳动，具体劳动是指生产一定使用价值的具体形式的劳动。抽象劳动是指撇开一切具体形式的、无差别的一般人类劳动。具体劳动创造使用价值，抽象劳动形成商品的价值。

具体劳动和抽象劳动也是对立统一的关系。

统一性：具体劳动和抽象劳动在时间和空间上是统一的，是同一劳动过程不可分割的两个方面。

对立性 ： 具体劳动所反映的是人与自然的关系 ，是劳动的自然属性 ，而抽象劳动所反映的是商品生产者的社会关系 ，是劳动的社会属性。

##### **商品的价值量**

决定商品价值量的是生产商品的社会必要劳动时间（在现有的社会正常的生产条件下，在社会平均的劳动熟练程度和劳动强度下制造某种使用价值所需要的劳动时间。

### **二、价值规律及其作用**

![价值规律](C:\Users\16536\OneDrive - stu.hit.edu.cn\Files\2022Autumn\马克思主义基本原理\考试复习\价值规律.png)

### **一、资本主义制度的确立**

资本的原始积累

### **二、劳动力成为商品与货币转换为资本**

商品流通公式
$$
W-G-W
$$
W是商品，G是流通中的货币，表明商品流通的目的是获得使用价值。

资本总公式
$$
G-W-G'
$$
G是作为资本的货币,G'代表的是价值增值后的货币，表明资本运动的一般目的是价值增殖

#### 劳动力成为商品的基本条件

1. 劳动者在法律上是自由人，能够把自己的劳动力当作自己的商品来支配。

2. 劳动者没有任何生产资料，没有生活资料来源，因而不得不靠出卖劳动力为生。

劳动力商品具有使用价值和价值
$$
劳动力的价值
\left\{ 
\begin{matrix}
维持劳动者本人生存所必需的生活资料的价值 \\
维持劳动者家属的生存所必需的生活资料的价值 \\
劳动者接受教育和训练所支出的费用    \\
\end{matrix}
\right.
$$
劳动力的使用价值：是价值的源泉，在消费过程中能够创造新的价值，而且这个新的价值比劳动力本身的价值更大。

这个增殖的价值叫做**剩余价值**（用m表示）。而一旦货币购买的劳动力带来剩余价值，货币也就变成资本。

### **三、资本主义所有制**

实质：资本家凭借对生产资料的占有，在等价交换原则的掩盖下，雇佣工人从事劳动，占有雇佣工人的剩余价值。

#### **（一）价值剥削率**

**不变资本(c)**是以生产资料形态存在的资本。

**可变资本(v)**是用来购买劳动力的那部分资本。

资本主义商品的价值构成公式：
$$
W=c+v+m
$$
剩余价值律m'等于剩余价值与可变资本的比例，即：
$$
m'=m/v
$$
或写成：
$$
m'=剩余劳动/必要劳动=剩余劳动时间/必要劳动时间
$$

#### **（二）剩余价值生产的两种基本方法**

1. 绝对剩余价值

   > 必要劳动时间不变的条件下，由于延长工作日的长度或提高劳动强度而生产的剩余价值 

2. 相对剩余价值

   > 是指在工作日长度不变的情况下，通过缩短必要劳动时间而相对延长剩余劳动时间所生产的剩余价值

#### **（三）资本积累**

资本积累的本质，就是资本家不断地利用无偿占有的工人创造的剩余价值来扩大自己的资本规模，进一步扩大和加强对工人的剥削和统治。

**资本积累的历史趋势是资本主义制度的必然灭亡和社会主义制度的必然胜利。**

#### **（四）资本的循环周转与再生产**

产业资本的运动所需要的循环条件：一是产业资本的三种职能形式必须在空间上并存，二是产业资本的三种职能形式必须在时间上继起。

#### **（一）资本主义的基本矛盾**

<u>生产社会化</u>和<u>生产资料资本主义私人占有</u>之间的矛盾，是资本主义的基本矛盾。

#### **（二）资本主义经济危机**

基本特征（本质特征）：生产相对过剩

社会资本再生产的四个阶段：危机、萧条、复苏和高涨。

## **第三节 资本主义政治制度和意识形态**

资本主义的民主制度是与资本主义生产方式相适应而发展起来的。

宪法是资本主义国家法律制度的核心。

资本主义国家采用分权制衡的组织形式，即国家的立法权、行政权、司法权分别由三个权利主体独立行使。

# **第五章 资本主义的发展及其趋势**

### 一、垄断

两个阶段：从自由竞争到垄断

垄断不能消除的原因：

1. 垄断没有消除产生竞争的经济条件
2. 垄断必须通过竞争来维持
3. 社会生产是复杂多样的

**金融资本:**金融资本是由工业垄断资本和银行垄断资本融合在一起而形成的一种垄断资本。
$$
垄断价格
\left\{ 
\begin{matrix}
垄断高价 \\
垄断低价 \\
\end{matrix}
\right.
$$
**垄断高价：**垄断组织出售商品时规定的高于生产价格的价格

**垄断低价 ：**垄断组织在购买非垄断企业所生产的原材料等生产资料时规定的低于生产价格的价格

### 二、经济全球化

经济全球化的表现：
$$
\left\{ 
\begin{matrix}
生产全球化 \\
贸易全球化 \\
金融全球化 \\
\end{matrix}
\right.
$$
经济全球化的动因：
$$
\left\{ 
\begin{matrix}
科学技术的进步和生产力的发展为经济全球化提供了坚实的物质基础和根本的推动力 \\
\\
跨国公司的发展为经济全球化提供了适宜的企业组织形式 \\
\\
各国公司经济体制的变革和国际经济组织的发展是经济全球化的体制与组织保障 \\
\end{matrix}
\right.
$$
对发展中国家的积极作用：
$$
\left\{ 
\begin{matrix}
提供了先进技术和管理经验 \\
\\
提供更多的就业机会 \\
\\
推动发展中国家国际贸易发展 \\
\end{matrix}
\right.
$$
同时，经济全球化也是一把“双刃剑”，表现在：

1. 发达国家与发展中国家在经济全球化中的地位和收益不平等、不平衡。
2. 加剧了发展中国家的资源短缺和环境污染。
3. 一定程度上增加了经济风险。

面向未来?

>  推动经济全球化朝着更加开放、包容、普惠、平衡、共赢的方向发展

第二节，资本主义的新变化

第三节，资本主义的历史地位和发展趋势

# **第六章 社会主义的发展及其规律**、

## **第一节 社会主义**五百年的历史进程

马克思、恩格斯适应社会的需要，在新的历史条件下创立和发展了**唯物史观**和**剩余价值学说** ，为社会主义<u>从空想到科学</u>的飞跃奠定了坚实的理论基础

**无产阶级夺取政权的第一次伟大尝试：**1871年爆发的巴黎公社革命，是第一国际精神的产儿。

**第一个社会主义国家的建立：** 十月革命（11月7日，俄历10月25日）胜利

列宁领导的苏维埃俄国对社会主义道路的探索，大体上经历了三个时期：

1. 进一步巩固苏维埃政权时期
2. 外国武装干涉和国内战争时期即战时共产主义时期
3. 由战时共产主义转变为新经济政策时期

**苏联解体，东欧剧变的最根本原因：**放弃了社会主义道路，放弃了无产阶级专政，放弃了共产党的领导地位，放弃了马克思列宁主义，把社会主义建设和党的建设中的失误归咎于领袖个人。

## **第二节 科学社会主义基本原则**

关键是如何正确把握科学社会主义一般原则

![科学社会主义原则](C:\Users\16536\AppData\Roaming\Typora\typora-user-images\image-20221209015211996.png)   

**科学社会主义十大基本原则：**

1. 资本主义必然灭亡，社会主义必然胜利。
2. 无产阶级是最先进最革命的阶级，肩负着推翻资本主义旧世界、建立社会主义和共产主义新世界的历史革命。
3. 无产阶级革命是无产阶级进行斗争的最高形式，以建立无产阶级专政的国家为目的。
4. 社会主义社会要在生产资料公有制基础上组织生产，以满足全体社会成员的需要为生产的根本目的。
5. 社会主义社会要对社会生产进行有计划的指导和调节，实行按劳分配原则。
6. 社会主义社会要合乎自然规律的改造和利用自然，努力实现人与自然的和谐共生。
7. 社会主义社会必须坚持科学的理论指导，大力发展社会主义先进文化。
8. 无产阶级政党是无产阶级的先锋队，社会主义事业必须坚持无产阶级政党的领导。
9. 社会主义社会要大力解放和发展生产力，逐步消灭剥削和消除两极分化，实现共同富裕和社会全面进步，并最终向共产主义社会过渡。
10. 共产主义社会是人类最美好的社会，实现共产主义是共产党人的最高理想。

## **第三节** 在实践中探索现实社会主义的发展规律

![社会主义发展道路的多样性原因](C:\Users\16536\AppData\Roaming\Typora\typora-user-images\image-20221209020027829.png)

# **第七章 共产主义崇高理想及其最终实现**

## **第一节 展望未来社会主义新社会**

预见未来社会的方法论原则：

1. 在揭示人类社会发展一般规律的基础上指明社会发展的方向
2. 在剖析资本主义旧世界的过程中阐发未来新世界的特点
3. 在社会主义社会发展中不断深化对未来共产主义社会的认识
4. 立足于揭示未来社会的一般特征，而不可能对各种细节作具体描绘

共产主义社会的基本特征：

1. 物质极大丰富，消费资料按需分配
2. 社会关系高度和谐，人们精神境界极大提高
3. 实现每个人自由而全面的发展，人类从必然王国向自由王国飞跃

## **第二节 实现社会主义是历史发展的必然趋势**

![image-20221209021706271](C:\Users\16536\AppData\Roaming\Typora\typora-user-images\image-20221209021706271.png)

## 第三节 共产主义远大理想与中国特色社会主义共同理想

**坚持远大理想与共同理想的辩证统一**

共同理想：中国特色社会主义

远大理想：共产主义

正确把握两者关系：

1. 从时间上看，远大理想与共同理想的关系是最终理性与阶段性理想的关系。
2. 从层次上看，远大理想与共同理想的关系是最高纲领与最低纲领的关系。
3. 从范围上看，远大理想与共同理想的关系也是全人类理想与全体中国人民理想的关系。

**Comment by lmh12138** [comment]
很好很好，但是中间有一些图片未能成功上传，可以考虑上传pdf的形式，把图片重新加入再提一次issue吧
