### ISSUE TITLE
关于仓库的一些建议

### ISSUE THREAD

**Issue by longlin10086** [HITSZ-Auto/HITSZ-OpenAuto#40]
本人自动化大一在读，发现仓库目录与实际有略微出入：
1. 模电与模电实验为大二下开设课程，仓库路径放在了大二上
2. 大一下近代史也为考试课，仓库中缺少该目录
3. 另：可以考虑开一个存放文理通识、mooc答案或建议的文件夹

最后感谢学长一直在维护仓库，希望仓库能越做越大，越做越好

**Comment by MaxwellJay256** [comment]
近现代史的文件夹我在我的fork已经新建了，等几天就能提交

**Comment by lmh12138** [comment]
是这样的，关于课程目录的问题，是因为培养方案每年都在变化，20级的模电确实是在大二上进行的，我确实没有那么多精力进行仓库的维护，所以需要你们多多进行pr，把仓库做的更好

**Comment by phychi** [comment]
如果有新的资料可以联系谁？

**Comment by longlin10086** [comment]
> 如果有新的资料可以联系谁？

目前这个仓库是由lmh学长维护的，有新的资料可以fork仓库然后提pr。
当然你也可以把资料发我然后我来提交（
然后鉴于目前仓库维护问题我觉得可以开一个organization然后邀请同学一起维护。

**Comment by lmh12138** [comment]
HITSZ-OpenAuto现已迁移至HITSZ-Auto组织
