### ISSUE TITLE
Consider splitting OpenAuto into multiple repositories by courses?

### ISSUE THREAD

**Issue by MaxwellJay256** [HITSZ-Auto/HITSZ-OpenAuto#49]
我的想法是，既然 OpenAuto 已经有 organiziation 了，是否可以把所有的课程拆分成独立的仓库，然后把介绍、目录、使用说明等放到组织的 README：[.github](https://github.com/HITSZ-Auto/.github) 下。

这样的好处是当培养方案的课程变更时（比如模电课从大二上迁移到了大二下），只需要更改目录文件，而模电对应的仓库几乎不需要改动。而在 OpenAuto，需要剪切一个文件夹放到另一个文件夹下，这个操作在 git. 中可能是一个非常大的文件操作。

而且随着仓库不断更新，里面的大文件和历史记录会越来越多，想要克隆整个 OpenAuto 会变得越来越难。将仓库拆分可以降低维护难度。

仓库可以按照 “课程编号-课程名”来命名，比如微积分A 命名为“MATH1015A-CalculusA”。

当然，这会是一个比较艰难的工程，同时可能损失一些珍贵的贡献记录。请三思。

**Comment by longlin10086** [comment]
把所有课都拆分出去倒不太需要，可以保留OpenAuto仓库，部分课程（例如各类实验）这种可能每年会更新的课可以单独开仓库进行维护。

**Comment by lmh12138** [comment]
我觉得可以这么搞，三位新维护者可以开一次会议确定细节

**Comment by OliverWu515** [comment]
我也同意。是否可以保留OpenAuto仓库，但是里面的文件夹不保留具体的文件，只保留课程对应仓库的链接？

**Comment by MaxwellJay256** [comment]
> 我也同意。是否可以保留OpenAuto仓库，但是里面的文件夹不保留具体的文件，只保留课程对应仓库的链接？

可以。我现在有一个想法是在这学期寒假实施这个工程，仓库拆分结束后为 OpenAuto 添加所有必要的说明，最后设置为 public archive。

**Comment by TangLongbin** [comment]
> > 我也同意。是否可以保留OpenAuto仓库，但是里面的文件夹不保留具体的文件，只保留课程对应仓库的链接？
> 
> 可以。我现在有一个想法是在这学期寒假实施这个工程，仓库拆分结束后为 OpenAuto 添加所有必要的说明，最后设置为 public archive。

如果可以的话，我可以来帮忙。

**Comment by lmh12138** [comment]
long bin大四了吧，如果你要是有空的话可以把你设置为仓库维护者

**Comment by TangLongbin** [comment]
> long bin大四了吧，如果你要是有空的话可以把你设置为仓库维护者

正有此意，同时对于 Open Auto 的后续维护我也有一些想法。我正在写邮件，里面有详细的内容，一会儿请查收邮箱。
