### ISSUE TITLE
建议项目迁移到 HITSZ Org 下

### ISSUE THREAD

**Issue by qhhonx** [HITSZ-Auto/HITSZ-OpenAuto#50]
原 issue：https://github.com/hewei2001/HITSZ-OpenCS/issues/100#issuecomment-1772096811

> 很高兴看到 HITSZ 的学弟学妹们创建了这么好的项目，让它的价值可以持续放大。早些年我在读研期间创建了 [HITSZ](https://github.com/hitsz) Org，那会儿由于还没有招本科生整体活跃度比较低，目前我已经看到了 [hewei2001/HITSZ-OpenCS](https://github.com/hewei2001/HITSZ-OpenCS) 和 [HITSZ-Auto/HITSZ-OpenAuto](https://github.com/HITSZ-Auto/HITSZ-OpenAuto) 这两个活跃项目，希望可以将这两个项目迁移到 [HITSZ](https://github.com/hitsz) Org ，未来希望有更多的项目出现在 [HITSZ](https://github.com/hitsz) Org 下让它们持续影响后续的学弟学妹们。虽然作为 [HITSZ](https://github.com/hitsz) Org 创建者，但已经很久没有维护过了，所以希望有兴趣的/有精力的学弟学妹们来共同维护（根据情况作为 Member or Owner 身份加入）。

**Comment by lmh12138** [comment]
由于不同学院的课程培养方案和实际技能需求不同，我个人不是特别赞同将仓库放在一起，这样可能会一定程度的误导学弟学妹们（就比如大学物理，机电和计科学的就不同），所以我觉得我们还是作为分开的两个组织会比较好一点
